# Generated by Django 3.0.5 on 2020-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200531_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domaine',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('CL', ' Computation and Language'), ('CC', 'Computational Complexity'), ('CE', 'Computational Engineering, Finance, and Science'), ('CG', 'Computational Geometry'), ('GT', 'Computer Science and Game Theory'), ('CV', 'Computer Vision and Pattern Recognition'), ('CY', 'Computers and Society'), ('CR', 'Cryptography and Security'), ('DS', 'Data Structures and Algorithms'), ('DB', 'Databases'), ('DL', 'Digital Libraries'), ('DM', 'Discrete Mathematics'), ('Other', 'Other')], max_length=50, verbose_name='Domaine of expertise'),
        ),
    ]
